name: Pac-Man Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # Esto actualizará el gráfico cada día a medianoche
  push:
    branches:
      - main

jobs:
  pacman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pac-Man Contributions
        run: |
          curl -L https://github.com/PacHub/pachub/archive/refs/heads/master.zip -o pacman.zip
          unzip pacman.zip
          cd pachub-master  # Asegúrate de que esta sea la carpeta correcta después de descomprimir
          bash pachub.sh
